# Generated by Django 2.1.4 on 2018-12-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detailed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('store', models.CharField(max_length=64)),
                ('price', models.CharField(max_length=16)),
                ('remark', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('other', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='content',
            name='realname',
            field=models.CharField(max_length=640),
        ),
        migrations.AlterField(
            model_name='content',
            name='short',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie_list',
            name='rating_num',
            field=models.CharField(max_length=1000),
        ),
    ]
