# Generated by Django 2.1.4 on 2019-05-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0002_auto_20181225_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dou_name', models.CharField(max_length=1000)),
                ('dou_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
