# Generated by Django 2.1.4 on 2019-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0003_movie_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='mid_name',
            field=models.CharField(default=54, max_length=1000),
            preserve_default=False,
        ),
    ]
