# Generated by Django 2.1.4 on 2019-09-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('input', '0004_content_mid_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='wen_order_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=16)),
                ('order_amount', models.CharField(max_length=16)),
                ('status', models.CharField(max_length=16)),
                ('remark', models.CharField(max_length=64)),
                ('pay_time', models.DateField()),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
